### PR TITLE
Update mini_project.py

### PR DESCRIPTION
**Pull request by greekgnemesis**

### CODE REVIEW

**Comment by armh12** [comment]
Hello!
You used very good ideas to implement your code, but however, I mentioned some issues, that in my opinion, could be better.
1)'sys' library is unnecessary, 'exit()' function in standart library works well.
2)Instead of 'random.rangrade()' function, you could use 'random.randint()' function, cause it's more simple, and more suitable for this case.
3)You wrote huge amount of functions, you could write less of them and your code complexity would be lower.
4)You used 'format()' function instead of f-strings, just a note, f-strings are more widespread and more easy to understand.
5)Too complicated prints, they provide more information that real user needs.
At least, I liked your code, it's very good solution for this problem.I wish you good luck in your future projects!

**Comment by greekgnemesis** [comment]
Thank u very much <3
I will try my best to improve.

**Comment by Gevgor87** [comment]
Hello, Thank you for your job.
I read the comment below about issues and I think that I must not repeat all of them again. 
I can add that you must add () after a.lower. It must be a.lower(). That's why this part of code does not work.
The second thing change please /n to \n in the start input. It is only misprint, because you wrote right in other places.
I wish you a good luck! Thank you one more time.

**Comment by greekgnemesis** [comment]
Thank you for your feedback.

**Pull request merged**
